### PR TITLE
Fix samplerate ratio calculation

### PR DESCRIPTION
**Pull request by xioxin**

### CODE REVIEW

**Comment by meshula** [comment]
Thanks for the fix!

Down at line 438 and 445, in the totalPitchRate() function, there is one ratio for src/dst rates, as well as a detune value. One thing to check is that the totalPitchRate calculation is set up consistently. (https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune) I'd like to make a little test that shows the sample rate conversion and detune work together to get a correct result.

Could you describe the scenario where you encountered the problem? For example 44.1 to 48 conversion, or something like that?

**Comment by xioxin** [comment]
ac.sampleRate: 48000
musicClip->sampleRate: 44100
The output pitch becomes higher

**Comment by meshula** [comment]
Reproduced in a test program, thanks for the fix!

**Comment by meshula** [comment]
The test is here - https://github.com/LabSound/LabSoundDemo/commit/a988ee590fbb0bf0de1e0c32bf9cc6cb5fd784d7 - it plays a 440hz tone via oscillator, then plays a 440hz/22050 tone using the resampler, then it detunes by one octave. It all sounds good now.

**Pull request merged**
